In [82]:
import numpy as np
import pandas as pd

# Create a DataFrame from Python Objects

In [83]:
np.random.seed(101)
mydata = np.random.randint(0,99,(4,3))
mydata

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]])

In [84]:
myindex = ['RJ','AS','JK','TN']
mycols = ['Jan','Feb','Mar']

In [85]:
#help(pd.DataFrame)

In [86]:
df = pd.DataFrame(data=mydata)
df

    0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63

In [87]:
pd.DataFrame(data=mydata, index=myindex,columns=mycols)

    Jan  Feb  Mar
RJ   95   11   81
AS   70   63   87
JK   75    9   77
TN   40    4   63

In [88]:
d1 = {'a' : [1,2,3,4],
      'b' : [11,12,13,14]}

In [89]:
pd.DataFrame(d1)

   a   b
0  1  11
1  2  12
2  3  13
3  4  14

In [90]:
from google.colab import drive
drive.mount('/content/drive')

#mounting your google drive to this colab notebook

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [91]:
df = pd.read_csv('/content/drive/MyDrive/Daksh_Gururkul_IITG_May_2025/08_Pandas/tips.csv')
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

# Obtaining Basic Information About DataFrame

In [92]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [93]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [94]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [95]:
df.head(3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458

In [96]:
df.tail(6)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [97]:
df.sample(5)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
169,10.63,2.00,Female,Yes,Sat,Dinner,2,5.32,Amy Hill,3536332481454019,Sat1788
161,12.66,2.50,Male,No,Sun,Dinner,2,6.33,Brandon Oconnor,4406882156920533,Sun5879
69,15.01,2.09,Male,Yes,Sat,Dinner,2,7.50,Adam Hall,4700924377057571,Sat855
222,8.58,1.92,Male,Yes,Fri,Lunch,1,8.58,Jason Lawrence,3505302934650403,Fri6624
93,16.32,4.30,Female,Yes,Fri,Dinner,2,8.16,Natalie Nguyen,5181236182893396,Fri6963

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [99]:
df.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [100]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15

In [101]:
df.shape

(244, 11)

In [102]:
type(df.shape)

tuple

In [103]:
len(df)

244

# Selection and Indexing

In [104]:
#Grabing a Single Column
df['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [105]:
type(df['total_bill'])

pandas.core.series.Series

In [106]:
#Grab Multiple Columns

df[['total_bill','tip','sex']]

     total_bill   tip     sex
0         16.99  1.01  Female
1         10.34  1.66    Male
2         21.01  3.50    Male
3         23.68  3.31    Male
4         24.59  3.61  Female
..          ...   ...     ...
239       29.03  5.92    Male
240       27.18  2.00  Female
241       22.67  2.00    Male
242       17.82  1.75    Male
243       18.78  3.00  Female

[244 rows x 3 columns]

In [107]:
type(df[['total_bill','tip','sex']])

pandas.core.frame.DataFrame

In [108]:
#Create New Columns

In [109]:
df['tip_percentage'] = np.round(df['tip']*100/df['total_bill'],3)
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.945
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.054
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.659
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.978
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.681

In [110]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID',
       'tip_percentage'],
      dtype='object')

In [111]:
#df[['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
 #      'price_per_person',  'Payment ID',
  #     'tip_percentage','Payer Name', 'CC Number',]]


## For rearranging columns in a df

In [112]:
df[ 'tip_per_person'] = np.round(df['tip']/df['size'],2)
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage,tip_per_person
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.945,0.50
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.054,0.55
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.659,1.17
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.978,1.66
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.681,0.90

# Remove Columns

In [116]:
#df.drop('tip_percentage',axis=1,inplace=True)

In [118]:
#df

In [81]:
df = df.drop('tip_percentage',axis=1) #, inplace=True)

In [33]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_per_person
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,0.50
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,0.55
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,1.17
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,1.66
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,0.90

# Index Basics

In [34]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_per_person
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,0.50
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,0.55
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,1.17
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,1.66
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,0.90

In [35]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [36]:
df = df.set_index('Payment ID')

In [37]:
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,tip_per_person
Payment ID,,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,0.50
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,0.55
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,1.17
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,1.66
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,0.90
...,...,...,...,...,...,...,...,...,...,...,...
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,1.97
Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,1.00
Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,1.00
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,0.88
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,1.50

In [38]:
df = df.reset_index()

In [39]:
df

,Payment ID,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,tip_per_person
0,Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,0.50
1,Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,0.55
2,Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,1.17
3,Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,1.66
4,Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,0.90
...,...,...,...,...,...,...,...,...,...,...,...,...
239,Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,1.97
240,Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,1.00
241,Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,1.00
242,Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,0.88
243,Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,1.50

# Grabbing a Row

In [40]:
df = df.set_index('Payment ID')
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,tip_per_person
Payment ID,,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,0.50
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,0.55
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,1.17
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,1.66
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,0.90

In [41]:
#Grab a single row

df.iloc[243] #index location

total_bill                     18.78
tip                              3.0
sex                           Female
smoker                            No
day                             Thur
time                          Dinner
size                               2
price_per_person                9.39
Payer Name           Michelle Hardin
CC Number           3511451626698139
tip_per_person                   1.5
Name: Thur672, dtype: object

In [42]:
df.tail(1)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,tip_per_person
Payment ID,,,,,,,,,,,
Thur672,18.78,3.0,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,1.5

In [43]:
#name based
df.loc['Sun4458']

total_bill                     21.01
tip                              3.5
sex                             Male
smoker                            No
day                              Sun
time                          Dinner
size                               3
price_per_person                 7.0
Payer Name            Travis Walters
CC Number           6011812112971322
tip_per_person                  1.17
Name: Sun4458, dtype: object

In [44]:
df.iloc[2]

total_bill                     21.01
tip                              3.5
sex                             Male
smoker                            No
day                              Sun
time                          Dinner
size                               3
price_per_person                 7.0
Payer Name            Travis Walters
CC Number           6011812112971322
tip_per_person                  1.17
Name: Sun4458, dtype: object

# Grab multiple Rows

In [45]:
df.iloc[11:21]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,tip_per_person
Payment ID,,,,,,,,,,,
Sun6686,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4577817359320969,1.25
Sun1300,15.42,1.57,Male,No,Sun,Dinner,2,7.71,Chad Harrington,577040572932,0.78
Sun2971,18.43,3.00,Male,No,Sun,Dinner,4,4.61,Joshua Jones,6011163105616890,0.75
Sun3848,14.83,3.02,Female,No,Sun,Dinner,2,7.42,Vanessa Jones,30016702287574,1.51
Sun1878,21.58,3.92,Male,No,Sun,Dinner,2,10.79,Matthew Reilly,180073029785069,1.96
Sun9715,10.33,1.67,Female,No,Sun,Dinner,3,3.44,Elizabeth Foster,4240025044626033,0.56
Sun2998,16.29,3.71,Male,No,Sun,Dinner,3,5.43,John Pittman,6521340257218708,1.24
Sun2789,16.97,3.50,Female,No,Sun,Dinner,3,5.66,Laura Martinez,30422275171379,1.17
Sat9213,20.65,3.35,Male,No,Sat,Dinner,3,6.88,Timothy Oneal,6568069240986485,1.12
Sat1709,17.92,4.08,Male,No,Sat,Dinner,2,8.96,Thomas Rice,4403296224639756,2.04

In [46]:
df.iloc[[34,213,109,156]]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,tip_per_person
Payment ID,,,,,,,,,,,
Sat8124,17.78,3.27,Male,No,Sat,Dinner,2,8.89,Jacob Castillo,3551492000704805,1.64
Sat1374,13.27,2.50,Female,Yes,Sat,Dinner,2,6.64,Robin Andersen,580140531089,1.25
Sat2614,14.31,4.00,Female,Yes,Sat,Dinner,2,7.16,Amanda Anderson,375638820334211,2.00
Sun7518,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,0.83

In [47]:
df.loc[['Sun7518','Sun1300']]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,tip_per_person
Payment ID,,,,,,,,,,,
Sun7518,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,0.83
Sun1300,15.42,1.57,Male,No,Sun,Dinner,2,7.71,Chad Harrington,577040572932,0.78

# Remove Rows

In [48]:
df.drop('Sun1300')

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,tip_per_person
Payment ID,,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,0.50
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,0.55
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,1.17
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,1.66
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,0.90
...,...,...,...,...,...,...,...,...,...,...,...
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,1.97
Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,1.00
Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,1.00
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,0.88
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,1.50

In [49]:
df.drop(index=df.index[[1,2,13]])

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,tip_per_person
Payment ID,,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,0.50
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,1.66
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,0.90
Sun9679,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,1.18
Sun5985,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2223727524230344,1.00
...,...,...,...,...,...,...,...,...,...,...,...
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,1.97
Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,1.00
Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,1.00
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,0.88
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,1.50