In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Daksh_Gururkul_IITG_May_2025/08_Pandas/tips.csv')
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

# Apply Method

In [ ]:
n1 = 410

In [ ]:
'*'*12+str(n1)[-4:]

'************410'

In [ ]:
def mask_cc(n):
  return '*'*12+str(n)[-4:]

In [ ]:
mask_cc(4676137647685994)

'************5994'

In [ ]:
df['masked_cc'] = df['CC Number'].apply(mask_cc)
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_cc
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,************3410
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,************9230
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,************1322
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,************5994
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,************7221

In [ ]:
def cat_customer(amt):
  if amt < 10:
    return '$'
  elif amt >= 10 and amt <= 17:
    return '$$'
  else:
    return '$$$'

In [ ]:
df['cust_category'] = df['total_bill'].apply(cat_customer)
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_cc,cust_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,************3410,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,************9230,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,************1322,$$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,************5994,$$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,************7221,$$$

# apply with lambda

In [ ]:
df['CC Number'].apply(lambda n : '*'*12+str(n)[-4:])

0      ************3410
1      ************9230
2      ************1322
3      ************5994
4      ************7221
             ...
239    ************2842
240    ************5404
241    ************7196
242    ************0950
243    ************8139
Name: CC Number, Length: 244, dtype: object

In [ ]:
df['total_bill'].apply(lambda b : np.round(b*1.05,2))

0      17.84
1      10.86
2      22.06
3      24.86
4      25.82
       ...
239    30.48
240    28.54
241    23.80
242    18.71
243    19.72
Name: total_bill, Length: 244, dtype: float64

In [ ]:
#sort_values

df.sort_values('tip',ascending=False)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_cc,cust_category
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,************8236,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,************5212,$$$
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239,************9808,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,************0595,$$$
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025,************8508,$$$
...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,************3410,$$
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801,************6887,$
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780,************6392,$
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455,************5267,$
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032,************3965,$$

In [ ]:
df.sort_values(['size','tip'])

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_cc,cust_category
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455,************5267,$
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801,************6887,$
82,10.07,1.83,Female,No,Thur,Lunch,1,10.07,Julie Moody,630413282843,Thur4909,************2843,$$
222,8.58,1.92,Male,Yes,Fri,Lunch,1,8.58,Jason Lawrence,3505302934650403,Fri6624,************0403,$
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780,************6392,$
...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4210875236164664,Sun9176,************4664,$$$
125,29.80,4.20,Female,No,Thur,Lunch,6,4.97,Angela Sanchez,503857080488,Thur3948,************0488,$$$
143,27.05,5.00,Female,No,Thur,Lunch,6,4.51,Regina Jones,4311048695487,Thur6179,************5487,$$$
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518,************3321,$$$
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025,************8508,$$$

# Correlation

In [ ]:
df.corr(numeric_only=True)

                  total_bill       tip      size  price_per_person  CC Number
total_bill          1.000000  0.675734  0.598315          0.647554   0.104576
tip                 0.675734  1.000000  0.489299          0.347405   0.110857
size                0.598315  0.489299  1.000000         -0.175359  -0.030239
price_per_person    0.647554  0.347405 -0.175359          1.000000   0.135240
CC Number           0.104576  0.110857 -0.030239          0.135240   1.000000

In [ ]:
df[['total_bill','tip']].corr()

            total_bill       tip
total_bill    1.000000  0.675734
tip           0.675734  1.000000

In [ ]:
#idxmin and idxmax
df['price_per_person'].max()

20.27

In [ ]:
df['price_per_person'].idxmax()

184

In [ ]:
df.iloc[184]

total_bill                     40.55
tip                              3.0
sex                             Male
smoker                           Yes
day                              Sun
time                          Dinner
size                               2
price_per_person               20.27
Payer Name               Stephen Cox
CC Number           3547798222044029
Payment ID                   Sun5140
masked_cc           ************4029
cust_category                    $$$
Name: 184, dtype: object

In [ ]:
df['price_per_person'].min()

2.88

In [ ]:
df['price_per_person'].idxmin()

92

In [ ]:
#Value Counts
df.head(2)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_cc,cust_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,************3410,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,************9230,$$

In [ ]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [ ]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [ ]:
#replace

df['day'].replace(to_replace='Sun',value='Sunday')

0      Sunday
1      Sunday
2      Sunday
3      Sunday
4      Sunday
        ...
239       Sat
240       Sat
241       Sat
242       Sat
243      Thur
Name: day, Length: 244, dtype: object

In [ ]:
#map

my_map = {'Sat':'Saturday',
          'Sun':'Sunday',
          'Thur':'Thursday'}

In [ ]:
df['day'].map(my_map)

0        Sunday
1        Sunday
2        Sunday
3        Sunday
4        Sunday
         ...
239    Saturday
240    Saturday
241    Saturday
242    Saturday
243    Thursday
Name: day, Length: 244, dtype: object

In [ ]:
#unique

df['size'].unique()

array([2, 3, 4, 1, 6, 5])

In [ ]:
df['time'].unique()

array(['Dinner', 'Lunch'], dtype=object)

In [ ]:
#nunique
df['size'].nunique()

6

In [ ]:
df['cust_category'].nunique()

3

In [ ]:
df['time'].nunique()

2

#Duplicates

In [ ]:
df.duplicated() #first instance of a duplicated row in your df

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [ ]:
simple_df = pd.DataFrame([[1,2,2],[1,2,2],[1,2,2]],['a','b','c'])
simple_df

   0  1  2
a  1  2  2
b  1  2  2
c  1  2  2

In [ ]:
simple_df.duplicated()

a    False
b     True
c     True
dtype: bool

In [ ]:
simple_df.drop_duplicates()

   0  1  2
a  1  2  2

In [ ]:
simple_df[simple_df.duplicated()]

   0  1  2
b  1  2  2
c  1  2  2

In [ ]:
simple_df

   0  1  2
a  1  2  2
b  1  2  2
c  1  2  2

In [ ]:
#between
df[df['total_bill'].between(left=10,right=20,inclusive='both')]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_cc,cust_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,************3410,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,************9230,$$
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377,Sun6820,************0377,$$
9,14.78,3.23,Male,No,Sun,Dinner,2,7.39,Jerome Abbott,3532124519049786,Sun3775,************9786,$$
10,10.27,1.71,Male,No,Sun,Dinner,2,5.14,William Riley,566287581219,Sun2546,************1219,$$
...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,15.53,3.00,Male,Yes,Sat,Dinner,2,7.76,Tracy Douglas,4097938155941930,Sat7220,************1930,$$
235,10.07,1.25,Male,No,Sat,Dinner,2,5.04,Sean Gonzalez,3534021246117605,Sat4615,************7605,$$
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032,************3965,$$
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,************0950,$$$
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,************8139,$$$

In [ ]:
df[df['size'].between(left=2,right=4,inclusive='neither')]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_cc,cust_category
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,************9230,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,************1322,$$$
16,10.33,1.67,Female,No,Sun,Dinner,3,3.44,Elizabeth Foster,4240025044626033,Sun9715,************6033,$$
17,16.29,3.71,Male,No,Sun,Dinner,3,5.43,John Pittman,6521340257218708,Sun2998,************8708,$$
18,16.97,3.50,Female,No,Sun,Dinner,3,5.66,Laura Martinez,30422275171379,Sun2789,************1379,$$
19,20.65,3.35,Male,No,Sat,Dinner,3,6.88,Timothy Oneal,6568069240986485,Sat9213,************6485,$$$
35,24.06,3.60,Male,No,Sat,Dinner,3,8.02,Joseph Mullins,5519770449260299,Sat632,************0299,$$$
36,16.31,2.00,Male,No,Sat,Dinner,3,5.44,William Ford,3527691170179398,Sat9139,************9398,$$
37,16.93,3.07,Female,No,Sat,Dinner,3,5.64,Erin Lewis,5161695527390786,Sat6406,************0786,$$
38,18.69,2.31,Male,No,Sat,Dinner,3,6.23,Brandon Bradley,4427601595688633,Sat4056,************8633,$$$
39,31.27,5.00,Male,No,Sat,Dinner,3,10.42,Mr. Brandon Berry,6011525851069856,Sat6373,************9856,$$$
40,16.04,2.24,Male,No,Sat,Dinner,3,5.35,Adam Edwards,3544447755679420,Sat8549,************9420,$$
48,28.55,2.05,Male,No,Sun,Dinner,3,9.52,Austin Fisher,6011481668986587,Sun4142,************6587,$$$
64,17.59,2.64,Male,No,Sat,Dinner,3,5.86,Michael Johnson,2222114458088108,Sat1667,************8108,$$$
65,20.08,3.15,Male,No,Sat,Dinner,3,6.69,Justin Dixon,180021262464926,Sat6840,************4926,$$$
71,17.07,3.00,Female,No,Sat,Dinner,3,5.69,Teresa Fisher,5442222963796367,Sat3469,************6367,$$$
102,44.30,2.50,Female,Yes,Sat,Dinner,3,14.77,Heather Cohen,379771118886604,Sat6240,************6604,$$$
112,38.07,4.00,Male,No,Sun,Dinner,3,12.69,Jeff Lopez,3572865915176463,Sun591,************6463,$$$
114,25.71,4.00,Female,No,Sun,Dinner,3,8.57,Katie Smith,5400160161311292,Sun6492,************1292,$$$
129,22.82,2.18,Male,No,Thur,Lunch,3,7.61,Raymond Torres,4855776744024,Thur9424,************4024,$$$
146,18.64,1.36,Female,No,Thur,Lunch,3,6.21,Kelly Estrada,60463302327,Thur3941,************2327,$$$
152,17.26,2.74,Male,No,Sun,Dinner,3,5.75,Gregory Smith,4292362333741,Sun5205,************3741,$$$
162,16.21,2.00,Female,No,Sun,Dinner,3,5.40,Jennifer Baird,4227834176859693,Sun5521,************9693,$$
165,24.52,3.48,Male,No,Sun,Dinner,3,8.17,Jacob Hansen,4031116007387,Sun9043,************7387,$$$
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,************8236,$$$
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337,************9910,$$$
186,20.90,3.50,Female,Yes,Sun,Dinner,3,6.97,Heidi Atkinson,4422858423131187,Sun4254,************1187,$$$
188,18.15,3.50,Female,Yes,Sun,Dinner,3,6.05,Glenda Wiggins,578329325307,Sun430,************5307,$$$
189,23.10,4.00,Male,Yes,Sun,Dinner,3,7.70,Richard Stevens,3560193117506187,Sun1821,************6187,$$$
200,18.71,4.00,Male,Yes,Thur,Lunch,3,6.24,Jason Conrad,4581233003487,Thur6048,************3487,$$$
205,16.47,3.23,Female,Yes,Thur,Lunch,3,5.49,Carly Reyes,4787787236486,Thur8084,************6486,$$
206,26.59,3.41,Male,Yes,Sat,Dinner,3,8.86,Daniel Owens,38971087967574,Sat1,************7574,$$$
210,30.06,2.00,Male,Yes,Sat,Dinner,3,10.02,Shawn Mendoza,30184049218122,Sat8361,************8122,$$$
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4922302538691962,Sat3374,************1962,$$$
223,15.98,3.00,Female,No,Fri,Lunch,3,5.33,Mary Rivera,5343428579353069,Fri6014,************3069,$$
231,15.69,3.00,Male,Yes,Sat,Dinner,3,5.23,Jason Parks,4812333796161,Sat6334,************6161,$$
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777,************3727,$$$
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,************2842,$$$

In [ ]:
#nlargest
df.nlargest(10,'tip')[['Payer Name','masked_cc']]

            Payer Name         masked_cc
170      Gregory Clark  ************8236
212    Alex Williamson  ************5212
23      Lance Peterson  ************9808
59         Brian Ortiz  ************0595
141     Steven Carlson  ************8508
183  Dr. Michael James  ************9162
214    Marissa Jackson  ************1962
47        James Barnes  ************4186
239      Michael Avila  ************2842
88        Roger Taylor  ************9955

In [ ]:
df.nlargest(3,['size','tip'])

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_cc,cust_category
141,34.30,6.7,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025,************8508,$$$
143,27.05,5.0,Female,No,Thur,Lunch,6,4.51,Regina Jones,4311048695487,Thur6179,************5487,$$$
156,48.17,5.0,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518,************3321,$$$

In [ ]:
df.nlargest(5,'tip')

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_cc,cust_category
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,************8236,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,************5212,$$$
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239,************9808,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,************0595,$$$
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025,************8508,$$$

In [ ]:
#nsmallest
df.nsmallest(5,'tip')

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_cc,cust_category
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455,************5267,$
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780,************6392,$
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801,************6887,$
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032,************3965,$$
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,************3410,$$