In [1]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Concatenation

In [2]:
data_one = {
    'A' : ['A0', 'A1','A2','A3'],
    'B' : ['B0','B1','B2','B3']
}


data_two = {
    'C' : ['C0','C1','C2','C3'],
    'D' : ['D0','D1','D2','D3']
}

In [3]:
one = pd.DataFrame(data_one)
two = pd.DataFrame(data_two)

In [4]:
one

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [5]:
two

    C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [6]:
#concatenate along rows (axis 0)

pd.concat([one,two],axis=0)

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3   A3   B3  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2
3  NaN  NaN   C3   D3

In [8]:
pd.concat([one,two],axis=1) #concatenate along columns (axis 1)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [9]:
data_three = {
    'A' : ['C0','C1','C2','C3'],
    'B' : ['D0','D1','D2','D3']
}

three = pd.DataFrame(data_three)
three

    A   B
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [10]:
pd.concat([one,three]) #default axis is 0

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

# Merge

In [30]:
reg = pd.DataFrame(
    {
        'reg_id' : [1,2,3,4],
        'name' : ['A','B','C','D']
    }
)

In [31]:
logins = pd.DataFrame(
    {
        'log_id' : [1,2,3,4],
        'name' : ['X','A','Y','B']
    }
)

In [32]:
reg

   reg_id name
0       1    A
1       2    B
2       3    C
3       4    D

In [33]:
logins

   log_id name
0       1    X
1       2    A
2       3    Y
3       4    B

In [34]:
pd.merge(reg,logins,how='inner',on='name')

   reg_id name  log_id
0       1    A       2
1       2    B       4

In [19]:
pd.merge(reg,logins,how='outer',on='name')

   reg_id name  log_id
0     1.0    A     2.0
1     2.0    B     4.0
2     3.0    C     NaN
3     4.0    D     NaN
4     NaN    X     1.0
5     NaN    Y     3.0

In [18]:
pd.merge(logins,reg,how='outer',on='name')

   log_id name  reg_id
0     2.0    A     1.0
1     4.0    B     2.0
2     NaN    C     3.0
3     NaN    D     4.0
4     1.0    X     NaN
5     3.0    Y     NaN

In [20]:
pd.merge(reg,logins,how='left',on='name')

   reg_id name  log_id
0       1    A     2.0
1       2    B     4.0
2       3    C     NaN
3       4    D     NaN

In [21]:
pd.merge(reg,logins,how='right',on='name')

   reg_id name  log_id
0     NaN    X       1
1     1.0    A       2
2     NaN    Y       3
3     2.0    B       4